version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  app:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env